name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"   # optional: rebuild every Sunday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/piqueserver:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
